### ISSUE TITLE
Hackfix to Maelstrom

### ISSUE THREAD

**Issue by Saphix16** [Duskhaven/Bug-Reports#1094]
Yesterday a hackfix was applied to counteract the resetting of a shamans swing timer whenever they would cast LB with maelstrom pcos. While I do think this was a good bandaid it does seem to only apply to Dual Wielding and not 2H. I'd assume it was made so to avoid elemental shamans taking advantage of this but in the process 2H also lost acces to this feature. Therefore I'd suggest also applying this to the talent Storm Infuser 3/3 or Maelstrom Weapon 5/5, assuming it was done by talents. Hope to see this fixed so us 2H shamans won't have to suffer.

**Comment by plasma-93** [comment]
Should definitely apply to 2h too as it's an issue for both.

I would suggest moving wherever the trigger is (maybe dual wield spec?) to 5/5 Maelstrom and include it in the talent description because it is kinda cool :D

And although it is a hackfix I think it feels pretty cool kekw. If it was possible to change the lightning bolt animation to a special attack weapon swing instead of a cast when you have maelstrom that would make it feel way less weird.

**Comment by plasma-93** [comment]
Also tested: Doesn't work for tank spec for likely the same reason though it is much less important for them

**Comment by Duskhaven** [comment]
This belongs in the class thread or suggestion forum
