### ISSUE TITLE
Scarlet Will Bug - Disc Priest

### ISSUE THREAD

**Issue by Hashkandiqt** [Duskhaven/Bug-Reports#1330]

**Comment by TheScarletCrusade** [comment]
I think it's supposed to be "self only" since it says "your haste", and to be melee haste for monks..

BUT even there, it doesn't work. it doesn't speed up melee weapons. Not on stats, and I even tried to wear a slow staff to try and it doesn't speed up anything.

Please fix this for monks, Power infusion is useless as monk right now.

https://cdn.discordapp.com/attachments/823579799028105236/1107718103904817302/image.png
