### ISSUE TITLE
Tinker: Mortal Shots talent doesnt work

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1572]
Abilities that are not getting the extra crit damage: Aimed Shot, Scrap Bullet, Heated Bullet, Chimaera Shot, Machine Gun, Rapid Shot

**Comment by GoldWarr** [comment]
This bug has been reported 2 times but i understand that certian bugs have prior above others totally understandable.

Hunter abilities not getting "Mortal Shot" talent bonus : Arcane Shot, Aimed Shot, Serpent Sting, Chimera Shot , Rapid Shot, Volley, Multi-shot.

honestly all Stings or Shots are affected by this, since "Mortal Shot" talent affects every ability in the game for Hunters.
