### ISSUE TITLE
Monk abilites are not working correctly.

### ISSUE THREAD

**Issue by TyrsHD** [Duskhaven/Bug-Reports#1676]
Thrash kick and Firestorm Kick is supposed to hit "all enemies infront of the monk" but it actually has a cap of 4, which causes mass pulls above +4 targets to be really funky.

**Comment by Duskhaven** [comment]
Intended

**Comment by baelbael** [comment]
The issue is that the changelog from 06/05/2023 states "Burning Fists and Fist of the Tiger now deal reduced damage beyond 3 targets" but in reality it only hits those three targets and deals absolutely no damage to additional ones. 

This should either be fixed or clarified if you did in fact mean "Burning Fists and Fist of the Tiger can now only damage three targets per cast and deals no further damage to enemies besides those 3.
