### ISSUE TITLE
Fiery Weapon Enchant - Not applying Deep Wounds

### ISSUE THREAD

**Issue by Feardonald** [Duskhaven/Bug-Reports#384]
**Fiery Weapon**
Permanently enchant a melee weapon to often strike for 40 additional fire damage.

**Deep Wounds**
Requires Melee Weapon
Your critical strikes cause the opponent to bleed, dealing 48% of your melee weapon's average damage over 6 sec.

Fiery Weapon is supposed to proc Deep Wounds with this version of the game.
Fiery Weapon critical strikes does not currently apply Deep Wounds debuff.

This worked in the original wotlk client.

Please let me know if you need anymore information.

Best Regards
Genjuro

**Comment by LVCJS** [comment]
October 14, 2022
Wrath of the Lich King Classic

Deep Wounds no longer triggers from non-Physical damage, such as the Fiery Weapon enchant.
Developers' note: Warriors have recently discovered that with the changes to Critical Strike Rating in Wrath, they can now get critical hits on spells quite often, and that those spell critical hits trigger Deep Wounds. Prior to Wrath, Warriors did not get increased spell critical chance from their gear. This discovery has resulted in players changing their enchantments on weapons to low-level enchantments that don't do much damage, but can trigger Deep Wounds and gain a significant damage increase over intended level 70-80 enchantments. Deep Wounds was never intended to benefit from these enchantments. Because of how Deep Wounds works, this advantage would continue to grow as Warriors gain better gear with more Critical Strike Rating. Additionally, some Warrior players are now looking for additional sources of spell damage from low-level sources, that they could use to gain increased Deep Wounds damage. We feel that this would only become more problematic, so it's best to resolve it quickly, before a lot of time and resources are invested into it. While it is a creative use of game mechanics, this would eventually be damaging to player and class fantasies, as well as very unintuitive for newer players.

**Comment by Colette00** [comment]
@therealbanjo 

your post is for Classic Woltk and not for the standard 3.3.5 Woltk Version privat servers are using.
It doesnt make much sense to quote a bluepost made from Blizzard for Classic Woltk.

**Comment by LVCJS** [comment]
And yet the reasoning behind the Blizzard nerf would apply to this server for the sake of its health and balance.

**Comment by Colette00** [comment]
The nerf you are asking for is nothing compared to what we have in Duskhaven.
When we have Demonhunters, Monks and Melee Hunters crowning themselves as top dps how could this compare to that?
Its unreasonable to look for Balance when Duskhaven grows on Chaos and crazy builds and speccs.

But i understand if your looking for more of a steady slow and blizzlike expierence then why not play Turtle Wow?..or Warmane? 

Even the metnioned reason of yours fails to be understandable because its only valid taking it to blizzlike servers.

**Comment by LVCJS** [comment]
Or they could balance fury towards arms damage without asking for "fiery weapon to proc deep wounds", that makes deep wounds 100% uptime, increases the dps upwards of 500 dps and is extremely hard to balance.

**Comment by Feardonald** [comment]
Hi,

Thanks for the input above.

It was indeed removed for the classic WOTLK, but was in the game for the original WOTLK.

Fury wont be able to gain deep wounds due to the level 60 cap.
Most likely it is not worth going for a hybrid with 20/31/0 (fury).

Hard to say beforehand how much it would help, but this would be for Arms and would most likely be useful.

Remember - this is a custom PVE server. 
Nothing ever was balanced with retail wow and especially not on custom tweaked private servers.

I would love to test it out, but can not because it is broken.
Being able to find new and unique ways to play the game is fun.

I personally do not think it will be too strong at level 60.

Best Regards
Genjuro
