### ISSUE TITLE
Gilneas starting zone bugs

### ISSUE THREAD

**Issue by Mapox69** [Duskhaven/Bug-Reports#735]
Samuel Williams quest - After entering the crypt, there are 4 standard knights named Samuel Williams. After completing the quests there, suddenly real Samuel Williams appears and runs away. In the cave the same.

After leaving the cave, Samuel Williams finally looks like real Samuel Williams and is only one, but bugs through ground all the way to Gilneas city.

In Gilneas city there is a problem with afk knights and mobs. Unless I get to the mobs aura, they don't attack the knights and knights don't attack them. They just stay there watching each other.

**Comment by Mapox69** [comment]
Plus as a warrior I could not charge in that crypt or cave, but it might be a purpose.

**Comment by harukaze3** [comment]
The charging issue is because the spell has a hard time recognising custom-made terrain. It will go away once you're out of there.

Samuel Williams has 4 copies to countermeasure his de-spawn time, so that's intended. As for why he's flying out of the crypt - he's just built different(jokes aside, same reason Charge has).

The knights just have poor AI.

> AD Haruka
